name: protoshaker
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: Kernel transformation to remove unused protocol types
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'
dependencies:
  kernel:
  dart_style:
  protobuf:
    path: ../protobuf
dev_dependencies:
  test:
#executables:
#  protoc-gen-dart: protoc_plugin
